version: "3.8"

services: 
  postgres:
    image: postgres:latest
    container_name: trial-task
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/trial_task
    ports:
      - "5432:5432"
  
  redis: 
    image: redis:alpine
    ports: 
      - "6379:6379"
    volumes: 
      - trial-task:/redis-data
  trial-task-api: 
    labels:
      kompose.service.type: LoadBalancer 
    build: 
      context: .
      dockerfile: Dockerfile
    image: trial-task-api:green.${DEPLOYMENT_VERSION}
    ports: 
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    depends_on: 
      - redis 

volumes:
  trial-task: