version: "3.8"

services: 
  postgres:
    image: postgres:latest
    container_name: trial-task-postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
  redis: 
    image: redis:alpine
    ports: 
      - "6379:6379"
    volumes: 
      - trial-task:/redis-data
  trial-task-api:
    labels:
      kompose.service.type: LoadBalancer 
    build: 
      context: .
      dockerfile: Dockerfile
    image: trial-task-api:blue.${DEPLOYMENT_VERSION}
    ports: 
      - "3000:3000"
    env_file:
      - .env.docker
    command: sh init.sh
    depends_on: 
      - redis 
      - postgres

volumes:
  trial-task: